Shopee/webapp/models.py
from webapp import db

# ORM for exchange rate table in mysql
class ExchangeRate(db.Model):
    __tablename__ = 'exchange_rates'

    from_country = db.Column(db.String(30), primary_key=True, nullable=False)
    to_country = db.Column(db.String(30), primary_key=True, nullable=False)
    date = db.Column(db.String(10),primary_key=True,nullable=False,index=True)
    rate = db.Column(db.DECIMAL, nullable=True)

Shopee/webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField
from wtforms.validators import DataRequired

# Register Form Skeleton; User enters currency rates for particular date which he/she wants to track
class RegisterRate(FlaskForm):
    date = StringField('Date')
    from_country = StringField('FromCountry', validators=[DataRequired()])
    to_country = StringField('ToCountry', validators=[DataRequired()])
    rate = StringField('Rate')
    submit = SubmitField('Submit')

# Track Form Skeleton; User enters date to track the currency rates on that given date
class TrackRate(FlaskForm):
    date = StringField('Date', validators=[DataRequired()])
    submit = SubmitField('Enter')

# Delete Form Skeleton; User enters currency he/she no longer wants to track
class DeleteRate(FlaskForm):
    from_country = StringField('FromCountry', validators=[DataRequired()])
    to_country = StringField('ToCountry', validators=[DataRequired()])
    submit = SubmitField('Submit')

Shopee/webapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from webapp.config import DATABASE,PASSWORD,USER,HOSTNAME,SECRET_KEY

# db variable initialization
db = SQLAlchemy()

# app initialization
def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config['SECRET_KEY'] = SECRET_KEY
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://%s:%s@%s/%s'%(USER, PASSWORD, HOSTNAME,DATABASE)

    Bootstrap(app)
    db.init_app(app)

    from webapp import models
    from webapp.controllers import myapp as myapp

    app.register_blueprint(myapp)

    return app

# Initialization function to create db on a new machine
def create_db():
            import sqlalchemy
            engine = sqlalchemy.create_engine('mysql://%s:%s@%s'%(USER, PASSWORD, HOSTNAME))
            engine.execute("CREATE DATABASE IF NOT EXISTS %s ;"%(DATABASE))
            engine.execute("USE %s ;" % (DATABASE))
            engine.execute("CREATE TABLE IF NOT EXISTS exchange_rates(from_country VARCHAR(30),to_country VARCHAR(30),date VARCHAR(10),rate DOUBLE(12,4) DEFAULT NULL,PRIMARY KEY (from_country,to_country,date));")

            return engine

Shopee/webapp/controllers.py
from webapp import db
from webapp.forms import RegisterRate, TrackRate,DeleteRate
from webapp.models import ExchangeRate
from flask import render_template,flash,Blueprint
from webapp.utils import validate,seven_day_average
import datetime

myapp = Blueprint('myapp', __name__)

# Homepage route
@myapp.route('/')
def homepage():
    return render_template('index.html')

# Register api to register currencies
@myapp.route('/register', methods=['GET','POST'])
def register():
    form = RegisterRate()
    now = datetime.datetime.now()
    if form.validate_on_submit():
        # Check if date format is correct YYYY-MM-DD
        if not validate(now.strftime("%Y-%m-%d") if not form.date.data else form.date.data):
            return render_template('incorrectDate.html')
        else:
            # Check if entry already exists in db or not
            exchangeObj = ExchangeRate.query.filter_by(date=now.strftime("%Y-%m-%d") if not form.date.data else form.date.data, from_country=form.from_country.data,
                                                       to_country=form.to_country.data).first()
            if exchangeObj:
                # Check if it is an update query
                if form.rate.data:
                    exchangeObj.rate=form.rate.data
                    if exchangeObj.rate:
                        db.session.commit()
                        return render_template('updateSuccess.html')
                    else:
                        render_template('updateFail.html')
                # Else it's an error as entry already present in database
                else:
                    return render_template('error.html')
            else:
                #Create entry if it is for first time
                exchangeRate = ExchangeRate(date=now.strftime("%Y-%m-%d") if not form.date.data else form.date.data,
                                            from_country=form.from_country.data,
                                            to_country=form.to_country.data,
                                            rate=None if not form.rate.data else form.rate.data)
                db.session.add(exchangeRate)
                db.session.commit()
                return render_template('successfull.html')

    return render_template('register.html',form=form)

# Track api to track currencies
@myapp.route('/track', methods=['GET','POST'])
def track():
    form = TrackRate()
    if form.validate_on_submit():
        # Check if date format is correct YYYY-MM-DD
        if not validate(form.date.data):
            return render_template('incorrectDate.html')
        else:
            # Get rates for the mentioned date
            rates = ExchangeRate.query.filter_by(date=form.date.data).order_by(ExchangeRate.from_country,ExchangeRate.to_country).all()
            if rates:
                # Calculate seven day average
                average_list = seven_day_average(form.date.data)
                return render_template('output.html', rates=rates,average_list=average_list)
            else:
                return render_template('noEntry.html')

    return render_template('track.html',form=form)

# Delete api to delete currencies
@myapp.route('/delete', methods=['GET','POST'])
def delete():
    form = DeleteRate()
    if form.validate_on_submit():
            # Fetch object from db which is to be deleted
            deleteObj = ExchangeRate.query.filter_by(from_country=form.from_country.data,
                                                     to_country=form.to_country.data).delete()
            if deleteObj or deleteObj!=0:
                db.session.commit()
                return render_template('deleteSuccess.html')
            else:
                return render_template('deleteFail.html')

    return render_template('delete.html',form=form)

Shopee/webapp/templates/delete.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Please enter the date</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/deleteFail.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Delete not implemented. Please check currencies added</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/deleteSuccess.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Delete successfull</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/error.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Entry present in database. No need to register</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/incorrectDate.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Incorrect data format, should be YYYY-MM-DD</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Foreign Currency Exchange</title>


    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">


</head>

<body>

    <div class="container">

        <div class="jumbotron">
            <h1>Forex App</h1>
            <p class="lead"></p>
            <p><a class="btn btn-lg btn-success" href="{{ url_for('myapp.register') }}" role="button">Add exchange rate</a>
            <p><a class="btn btn-lg btn-success" href="{{ url_for('myapp.track') }}" role="button">Track exchange rate</a>
            <p><a class="btn btn-lg btn-success" href="{{ url_for('myapp.delete') }}" role="button">Delete Exchange rate</a>
            </p>
        </div>

        {% block body %}
        {% endblock %}


    </div>
</body>

</html>

Shopee/webapp/templates/noEntry.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Entry not present in database. Register first to track</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/output.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    {%if not rates %}
        <h1>No data present for the date</h1>
    {%else%}
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">From</th>
              <th scope="col">To</th>
              <th scope="col">Rate</th>
              <th scope="col">7-day average</th>
            </tr>
          </thead>
          <tbody>
          {% for i in range(rates|length) %}
              <tr>
                  <td>{{rates[i].date}}</td>
                  <td>{{rates[i].from_country}}</td>
                  <td>{{rates[i].to_country}}</td>
                  {%if rates[i].rate is none%}
                     <td>Insuffficient data</td>
                  {%else%}
                     <td>{{rates[i].rate}}</td>
                  {% endif %}
                 {%if average_list[i] == 0.00%}
                     <td>Insuffficient data</td>
                  {%else%}
                     <td>
                      {{average_list[i]}}
                  </td>
                  {% endif %}

              </tr>

          {% endfor %}
          </tbody>
        </table>
     {% endif %}
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/successfull.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Successfull Registration</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/track.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Please enter the date</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/updateFail.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Update Fail</h1>
    <br/>
  </div>
</div>
{% endblock %}

Shopee/webapp/templates/updateSuccess.html
{% extends "index.html" %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Update Success</h1>
    <br/>
  </div>
</div>
{% endblock %}